### ISSUE TITLE
Trinket/TinyWireM incompatibility

### ISSUE THREAD

**Issue by rkline1963** [adafruit/Adafruit-MCP23008-library#4]
Since there is an include statement for Wire.h in the .cpp file, this library doesn't work with the suggested trick from Mike Barela's Getting Started with Adafruit Trinket of including TinyWireM and using #define Wire TinyWireM in the sketch.

**Comment by Sturla22** [comment]
Seems to have been solved, should be closed?

**Comment by evaherrada** [comment]
@Sturla22 this is solved by PR #12, correect?

**Comment by Sturla22** [comment]
No, I thought https://github.com/adafruit/Adafruit-MCP23008-library/commit/cda45c74e6e74d25cac0bbe03859402f19e637bd had solved it, but maybe I misunderstood the issue.

**Comment by evaherrada** [comment]
oh, yeah, didn't realize this issue was five years old. Yeah, that looks fixed.
