### ISSUE TITLE
Interrupts management

### ISSUE THREAD

**Issue by hbachetti** [adafruit/Adafruit-MCP23008-library#9]
I recently used your MCP23008 library.
The interrupts management is missing, so I tried to implement it myself by subclassing Adafruit_MCP23008 to add an enableInterrupts method.
But the write8 method and i2caddr member are "private".
I think it would be a good idea to turn them "protected" to allow people to add their own features.

Regards

**Comment by maxholgasson** [comment]
Hi, would you share your modified code? I'm also looking for using the MCP23008 with interrupt to wake up the processor from deep sleep
Best regards

**Comment by hbachetti** [comment]
absolutely

class MyMCP23008 : public Adafruit_MCP23008
{
  protected:
    void write8(uint8_t addr, uint8_t data);
    uint8_t i2caddr;

  public:  
    void enableInterrupts(uint8_t data);
};

void MyMCP23008::write8(uint8_t addr, uint8_t data) {
  Wire.beginTransmission(MCP23008_ADDRESS | i2caddr);
#if ARDUINO >= 100
  Wire.write((byte)addr);
  Wire.write((byte)data);
#else
  Wire.send(addr);  
  Wire.send(data);
#endif
  Wire.endTransmission();
}

void MyMCP23008::enableInterrupts(uint8_t data)
{
  this->write8(MCP23008_GPINTEN, data);
}

**Comment by maxholgasson** [comment]
Hello, thanks, May I ask you where I have to add or replace your code?

**Comment by maxholgasson** [comment]
Hi, I tried it now quite long to modifiy the lib with your code but failed. Could you tell me what I have to change of the original library or is your whole file available somewhere? that would be great

**Comment by hbachetti** [comment]
Failed ? Did you not succeed to compile ? or is it an execution problem ?
This is a code for a MYSENSORS remote command with 8 buttons
`
// Enable debug prints to serial monitor
//#define MY_DEBUG 

// Enable and select radio type attached
#define MY_RADIO_NRF24
//#define MY_RADIO_RFM69

#define MY_RF24_CE_PIN    7
#define MY_RF24_CS_PIN    8

#define CHILD_ID          1
#define MCP_INTERRUPT     3
#define SLEEP_TIME        10000

#include <MySensors.h>  
#include <Wire.h>
#include "Adafruit_MCP23008.h"

class MyMCP23008 : public Adafruit_MCP23008
{
  protected:
    void write8(uint8_t addr, uint8_t data);
    uint8_t i2caddr;

  public:  
    void enableInterrupts(uint8_t data);
};

void MyMCP23008::write8(uint8_t addr, uint8_t data) {
  Wire.beginTransmission(MCP23008_ADDRESS | i2caddr);
#if ARDUINO >= 100
  Wire.write((byte)addr);
  Wire.write((byte)data);
#else
  Wire.send(addr);  
  Wire.send(data);
#endif
  Wire.endTransmission();
}

void MyMCP23008::enableInterrupts(uint8_t data)
{
  this->write8(MCP23008_GPINTEN, data);
}

MyMCP23008 mcp;

MyMessage msgIrReceive(CHILD_ID, V_IR_RECEIVE);

void before()
{
}

void setup()  
{ 
  Serial.begin(115200);
  mcp.begin();
  for (int button = 0 ; button < 8 ; button++) {
    mcp.pinMode(button, INPUT);
    mcp.pullUp(button, HIGH);  // turn on a 100K pullup internally
    mcp.enableInterrupts(0xff);
  }
}

void presentation() {
  Serial.print("MYSENSORS REMOTE: ");
  // Send the sketch version information to the gateway and Controller
  sendSketchInfo("REMOTE", "1.1");
  present(CHILD_ID, S_IR);
  Serial.println("OK");
}

void loop() {
  static long lastDebounceTime = 0;
  Serial.println("INT3");
  if (lastDebounceTime == 0 || (millis() - lastDebounceTime) > 200) {
    lastDebounceTime = millis();
    uint8_t buttons = mcp.readGPIO();
    if (buttons != 0xff) {
      int value = (~buttons)&0xff;
      Serial.print("buttons: ");
      Serial.println(value, HEX);
      send(msgIrReceive.set(value));
    }
  }
  Serial.print("sleep on ");
  Serial.println(digitalPinToInterrupt(MCP_INTERRUPT));
  smartSleep(digitalPinToInterrupt(MCP_INTERRUPT), FALLING, SLEEP_TIME);
}

`

**Comment by caternuson** [comment]
Please try the new 2.0.0 release of the Adafruit-MCP23017-Arduino-Library. MCP23008 support has been moved there and includes updates that may address this issue.
